%% created-for: system-design-mastery
sequenceDiagram
  participant P0 as Client
  participant P1 as Inventory-Management Platfor
  participant P2 as Store
  P0 ->> P1: request
  P1 ->> P2: process
  P2 -->> P1: response
  P1 -->> P0: response
